# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simpo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'OAuthSwift', '~> 1.1.0'
  pod 'Prephirences/Cocoa'
  pod 'SwiftyJSON'
  # Pods for Simpo

end
